"""Creating a job, input validation, and job status/progress."""
import uuid

import pytest

from app.core.config import settings
from tests.helpers import error_of, job_payload, recipients


# --- Creating a job ---------------------------------------------------------------------------------------------


def test_create_job_returns_202_and_queues_the_job(client):
    response = client.post("/jobs", json=job_payload(recipients("Asha Rao", "Ben Okafor", "Chen Wei")))

    assert response.status_code == 202
    body = response.json()
    uuid.UUID(body["job_id"])
    assert body["status"] == "PENDING"
    assert body["status_url"] == f"/jobs/{body['job_id']}"
    assert body["progress"] == {
        "total": 3, "pending": 3, "generated": 0, "failed": 0, "invalid": 0, "percent_complete": 0.0,
    }

    # Nothing is generated by the API itself: the job waits in the queue for a worker.
    status = client.get(body["status_url"]).json()
    assert status["job"]["status"] == "PENDING"
    assert status["job"]["attempts"] == 0
    assert [(c["row_index"], c["recipient_name"], c["status"]) for c in status["certificates"]] == [
        (0, "Asha Rao", "PENDING"),
        (1, "Ben Okafor", "PENDING"),
        (2, "Chen Wei", "PENDING"),
    ]


def test_issue_date_defaults_to_today_and_issuer_is_optional(client):
    payload = job_payload(recipients("Asha Rao"))
    del payload["issue_date"], payload["issued_by"]

    response = client.post("/jobs", json=payload)

    assert response.status_code == 202
    job = client.get(response.json()["status_url"]).json()["job"]
    assert job["issue_date"] is not None
    assert job["issued_by"] is None


# --- Input validation ---------------------------------------------------------------------------------------------


@pytest.mark.parametrize(
    "change",
    [
        pytest.param({"course_name": None}, id="missing course name"),
        pytest.param({"course_name": "   "}, id="blank course name"),
        pytest.param({"course_name": "x" * 201}, id="course name too long"),
        pytest.param({"course_name": "数据科学"}, id="course name the font cannot print"),
        pytest.param({"issued_by": ""}, id="blank issuer"),
        pytest.param({"issue_date": "2026-13-01"}, id="invalid date"),
        pytest.param({"recipients": []}, id="no recipients"),
        pytest.param({"recipients": None}, id="missing recipients"),
        pytest.param({"recipients": ["Asha Rao"]}, id="recipient is not an object"),
        pytest.param(
            {"recipients": recipients("Asha Rao") * (settings.max_recipients_per_job + 1)}, id="too many recipients"
        ),
    ],
)
def test_malformed_request_is_rejected_with_422(client, change):
    payload = job_payload(recipients("Asha Rao"))
    for key, value in change.items():
        if value is None:
            del payload[key]
        else:
            payload[key] = value

    response = client.post("/jobs", json=payload)

    assert response.status_code == 422
    assert error_of(response)["code"] == "VALIDATION_ERROR"
    assert error_of(response)["details"][0]["field"].split(".")[1] in change  # points at the offending field


def test_invalid_recipients_are_marked_invalid_without_rejecting_the_valid_ones(client, run_worker):
    rows = [
        {"name": "Asha Rao", "email": "asha@example.com"},  # 0 valid
        {"name": "   ", "email": "blank@example.com"},  # 1 blank name
        {"name": "Bad Email", "email": "not-an-email"},  # 2 invalid email
        {"name": "शैलेंद्र", "email": "hindi@example.com"},  # 3 the built-in font can't print it
        {"name": "Asha Again", "email": "ASHA@example.com"},  # 4 same email as row 0
        {"email": "noname@example.com"},  # 5 name missing
        {"name": {"first": "Ben"}, "email": "ben@example.com"},  # 6 name is not a string
        {"name": "José Müller", "email": "jose@example.com"},  # 7 valid (Latin accents are fine)
    ]

    response = client.post("/jobs", json=job_payload(rows))

    assert response.status_code == 202
    assert response.json()["progress"]["invalid"] == 6
    run_worker()
    status = client.get(response.json()["status_url"]).json()
    by_row = {c["row_index"]: c for c in status["certificates"]}

    assert by_row[0]["status"] == by_row[7]["status"] == "GENERATED"
    assert {row for row, c in by_row.items() if c["status"] == "INVALID"} == {1, 2, 3, 4, 5, 6}
    assert {row: c["error_code"] for row, c in by_row.items() if c["status"] == "INVALID"} == {
        1: "INVALID_RECIPIENT",
        2: "INVALID_RECIPIENT",
        3: "INVALID_RECIPIENT",
        4: "DUPLICATE_EMAIL",
        5: "INVALID_RECIPIENT",
        6: "INVALID_RECIPIENT",
    }
    assert by_row[0]["error_code"] is None
    assert by_row[1]["error_message"] == "name: String should have at least 1 character"
    assert by_row[2]["error_message"].startswith("email: value is not a valid email address")
    assert by_row[3]["error_message"] == "name: contains characters the certificate font cannot render"
    assert by_row[4]["error_message"] == "email: duplicate of row 0"
    assert by_row[5]["error_message"] == "name: Field required"
    assert by_row[6]["error_message"] == "name: Input should be a valid string"
    # What the client sent is echoed back so they can find the row, and nothing is downloadable.
    assert by_row[2]["recipient_email"] == "not-an-email"
    assert by_row[6]["recipient_name"] == "{'first': 'Ben'}"
    assert by_row[2]["download_url"] is None
    assert status["job"]["status"] == "COMPLETED_WITH_ERRORS"


# --- Job status / progress ----------------------------------------------------------------------------------------


def test_progress_moves_from_pending_to_completed(client, run_worker):
    rows = recipients("Asha Rao", "Ben Okafor") + [{"name": "No Email"}]
    status_url = client.post("/jobs", json=job_payload(rows)).json()["status_url"]

    before = client.get(status_url).json()
    assert before["job"]["status"] == "PENDING"
    assert before["progress"] == {
        "total": 3, "pending": 2, "generated": 0, "failed": 0, "invalid": 1, "percent_complete": 33.3,
    }

    assert run_worker() == 1

    after = client.get(status_url).json()
    assert after["job"]["status"] == "COMPLETED_WITH_ERRORS"
    assert after["job"]["attempts"] == 1
    assert after["job"]["started_at"] is not None
    assert after["job"]["completed_at"] is not None
    assert after["progress"] == {
        "total": 3, "pending": 0, "generated": 2, "failed": 0, "invalid": 1, "percent_complete": 100.0,
    }


def test_job_with_only_valid_recipients_is_completed(client, run_worker):
    status_url = client.post("/jobs", json=job_payload(recipients("Asha Rao", "Ben Okafor"))).json()["status_url"]

    run_worker()

    assert client.get(status_url).json()["job"]["status"] == "COMPLETED"


def test_job_with_no_valid_recipients_fails(client, run_worker):
    rows = [{"name": "", "email": "a@example.com"}, {"name": "No Email"}]
    status_url = client.post("/jobs", json=job_payload(rows)).json()["status_url"]

    run_worker()

    status = client.get(status_url).json()
    assert status["job"]["status"] == "FAILED"
    assert status["progress"]["invalid"] == 2


def test_unknown_job_returns_404(client):
    response = client.get(f"/jobs/{uuid.uuid4()}")

    assert response.status_code == 404
    assert error_of(response)["code"] == "JOB_NOT_FOUND"
